### ISSUE TITLE
Sorry  ! Server is not responding

### ISSUE THREAD

**Issue by mudssrali** [Techistan/Whatsapp-Bot#12]
Even installing the complete dependencies, `server` is running fine.

**Comment by MrSlimCoder** [comment]
@Mudassar045 thank you for this issue actually this project is 1 year old and i didn't maintain server from that one year but i will try my best to resolve bugs and get back to you after that .

**Comment by MrSlimCoder** [comment]
I will get back to you after checking whole project I'm not closing this issue until it get fixed.
happy contributing !

**Comment by mudssrali** [comment]
Will wait. I'm just giving a try to `Techistan`s stuff :+1:

**Comment by MrSlimCoder** [comment]
That's great ! we also need people like you .
Thank you so much !

**Comment by mudssrali** [comment]
I'm burning warm bed sleeps, to learn as much as possible before landing into Pakistan's tech eco-system :pakistan: Nicer to know people like you already there to support and promote learning

**Comment by MrSlimCoder** [comment]
@Mudassar045 This is my responsibility as a Pakistani . Thank you for your kind words.

**Comment by MrSlimCoder** [comment]
@Mudassar045 I tested everything and the server is running on my system actually this is a production ready environment.
